### ISSUE TITLE
eks-eksctl page not found

### ISSUE THREAD

**Issue by SansGuidon** [joostvdg/joostvdg.github.io#12]
The page is referenced from https://joostvdg.github.io/cloudbees/cbc-eks/ 
When I try to reach https://joostvdg.github.io/cloudbees/cbc-eks/kubernetes/distributions/eks-eksctl/ , the page fails to load properly and shows a 404 not found error, despite the page source code still exists at  https://github.com/joostvdg/joostvdg.github.io/blob/master/kubernetes/distributions/eks-eksctl/index.html

**Comment by joostvdg** [comment]
Thanks, @MorganGeek , I've fixed the mistake (missing a `/` as prefix of the URL). 
The guide probably warrants a further update to bring it up to 2020 with regards to AWS configuration and CloudBees docs.

**Comment by SansGuidon** [comment]
Thank you @joostvdg  :-) 
Looking forward for your update. Quick question : Having only a few days ahead to setup a full eks on aws, would you suggest eksctl or terraform for long term maintenance ? :-D

**Comment by joostvdg** [comment]
Personally, I'd go for Terraform. But I've haven't done a complete setup with Terraform for EKS yet, so not sure if there are any caveats there.

**Comment by SansGuidon** [comment]
Thank you @joostvdg :-)
